### ISSUE TITLE
Credentials / secrets leaked in previous commits

### ISSUE THREAD

**Issue by IDisposable** [evoila/influxdb-firehose-nozzle#4]
Did a security review for an incoming patch (from Monsanto) and found some credentials / secrets were leaked in previous commits to this repository.  Since it's already been leaked, please make sure you have changed passwords / API tokens as appropriate on the services that were leaked.

https://github.com/evoila/influxdb-firehose-nozzle/blob/6eec8cfb12ed92955976e14f23f10934d4e88e0a/config/datadog-firehose-nozzle.json has exposed `DataDogAPI` credentials (later removed)

https://github.com/evoila/influxdb-firehose-nozzle/blob/7393b43a7940ee54ca4f2507bb787b117c443dc0/.travis.yml has `env / secure` blob (later removed)

https://github.com/evoila/influxdb-firehose-nozzle/blob/e88233b1901ee563f854780ec8311838a91e5289/.travis.yml has `COVERALLS_TOKEN / secure` blob (later removed)

https://github.com/evoila/influxdb-firehose-nozzle/blob/552874f82fdbb3f9ad5358eb713122ea9b70d979/config/influxdb-firehose-nozzle.json has the IP:PORT of an `InfluxDbUrl`, probably not an issue, but might be better to not have been leaked (later removed, then *restored* in  https://github.com/evoila/influxdb-firehose-nozzle/commit/79cf0227cdaa898a139ac8a2df641873c0f2f91b and *never removed* again)

**Comment by jhiemer** [comment]
@IDisposable thanks for the review. Those credentials are outdated and not running on an existing infrastructure anymore. Though I have changed the settings in influxdb-firehose-nozzle.json
